"""Report escaping: HTML, CSV formula injection, JSON structure, redaction."""

import json

from paramscout.models import DiffObservation, Endpoint, Finding, ProbeResult
from paramscout.reporting.csvreport import render_csv_report, sanitize_csv_value
from paramscout.reporting.htmlreport import render_html_report
from paramscout.reporting.jsonreport import render_json_report
from paramscout.reporting.models import metadata_block, row_from_finding
from paramscout.redaction import Redactor

ENDPOINT = Endpoint(
    id="e1",
    key="https://app.example.test/search",
    url="https://app.example.test/search?token=SUPERSECRET&next=/home",
    host="app.example.test",
    netloc="app.example.test",
)


def hostile_finding(param: str) -> Finding:
    probe = ProbeResult(
        param=param,
        canary="cafe12",
        http_status=200,
        observed_diffs=[DiffObservation("text", "normalized visible text changed")],
        reflected=True,
        reflect_contexts=["raw-body"],
        control_similar=False,
        reproduced=True,
        attempts=2,
    )
    return Finding(
        endpoint=ENDPOINT,
        param=param,
        category="unknown/general-purpose",
        discovery_score=0.9,
        discovery_label="high",
        behavior_score=0.85,
        behavior_label="high",
        priority="high",
        priority_reasons=["exact canary reflected; review output encoding"],
        probe=probe,
    )


def test_secret_redaction_applied_to_rows_and_context():
    redactor = Redactor()
    redactor.add_secret("SUPERSECRET")
    finding = hostile_finding("next")
    row = row_from_finding(finding, redactor)
    blob = json.dumps(row)
    assert "SUPERSECRET" not in blob
    assert "<redacted>" in blob


def test_csv_formula_injection_mitigated():
    assert sanitize_csv_value("=cmd()") == "'=cmd()"
    assert sanitize_csv_value("+1") == "'+1"
    assert sanitize_csv_value("-1") == "'-1"
    assert sanitize_csv_value("@SUM") == "'@SUM"
    assert sanitize_csv_value("\t0") == "'\t0"
    assert sanitize_csv_value("normal") == "normal"
    text = render_csv_report(
        [{"parameter": "=HYPERLINK(\"http://evil\")", "endpoint": "https://h/x", "category": "unknown"}]
    )
    assert "=HYPERLINK" in text
    assert "'=HYPERLINK" in text  # neutralized copy is present


def test_html_report_escapes_untrusted_content():
    redactor = Redactor()
    finding = hostile_finding('<script>alert("xss")</script>')
    row = row_from_finding(finding, redactor)
    metadata = metadata_block(
        command="scan",
        mode="active",
        status="ok",
        status_detail="",
        args={},
        scope_lines=["app.example.test"],
        totals={"requests": 5},
        limitations=[],
    )
    page = render_html_report(metadata, [row])
    assert "<script>alert" not in page  # raw payload must not appear
    assert "&lt;script&gt;alert" in page
    # footer attribution & support link present; no remote assets
    assert "Generated by ParamScout" in page
    assert "Mrdineshpathro" in page
    assert "https://buymeacoffee.com/mrdineshpathro" in page
    # fully self-contained: no remote assets, no script includes
    assert "<script src=" not in page
    assert "<link " not in page
    assert "googleapis" not in page and "cdn." not in page


def test_json_report_valid_and_structured():
    metadata = metadata_block(
        command="scan", mode="passive", status="ok", status_detail="",
        args={"active": False}, scope_lines=["x.test"], totals={"requests": 0},
        limitations=["none"],
    )
    redactor = Redactor()
    row = row_from_finding(hostile_finding("q"), redactor)
    payload = json.loads(render_json_report(metadata, [row]))
    assert payload["metadata"]["tool"] == "ParamScout"
    assert payload["metadata"]["version"] == "0.1.0"
    assert payload["findings"][0]["parameter"] == "q"
    assert payload["findings"][0]["reflection_status"].startswith("yes")
    assert payload["findings"][0]["validation_attempts"] == 2


def test_row_includes_all_required_fields():
    redactor = Redactor()
    row = row_from_finding(hostile_finding("url"), redactor)
    for key in (
        "endpoint", "parameter", "category", "source", "source_context",
        "discovery_confidence", "behavior_confidence", "manual_review_priority",
        "priority_reasons", "observed_differences", "reflection_status",
        "validation_attempts", "inconclusive", "status_note",
        "reproduction_request", "limitations",
    ):
        assert key in row, key
