"""Self-contained HTML report writer.

The report is fully static: all CSS is inline, there are no remote assets,
analytics, or tracking, and every untrusted value is HTML-escaped. Metadata
values (including the support link) are plain text attributes; nothing is
executed by merely opening the file.
"""

from __future__ import annotations

import html
from typing import Any, Iterable

from .csvreport import COLUMNS

_ESCAPE = html.escape

_PRIORITY_STYLE = {
    "high": "#7d1f1f",
    "medium": "#8a6116",
    "low": "#2c5f2d",
    "none": "#444444",
}

_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
         margin: 2rem auto; max-width: 96rem; padding: 0 1rem; color: #222; }}
  h1 {{ font-size: 1.5rem; }} h2 {{ font-size: 1.15rem; margin-top: 2rem; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 0.82rem; }}
  th, td {{ border: 1px solid #ccc; padding: 0.35rem 0.5rem; text-align: left;
           vertical-align: top; word-break: break-word; }}
  th {{ background: #f0f0f0; position: sticky; top: 0; }}
  tr:nth-child(even) td {{ background: #fafafa; }}
  code {{ background: #f4f4f4; padding: 0.05rem 0.25rem; border-radius: 3px; }}
  .pill {{ display:inline-block; padding:0.05rem 0.45rem; border-radius: 999px;
          color:#fff; font-weight:600; font-size:0.75rem; }}
  .meta {{ color:#555; }} footer {{ margin-top: 2.5rem; border-top: 1px solid #ddd;
          padding-top: 0.7rem; font-size: 0.8rem; color:#555; }}
  @media (prefers-color-scheme: dark) {{
     body {{ background:#121212; color:#ddd; }} th {{ background:#262626; }}
     tr:nth-child(even) td {{ background:#1a1a1a; }} .meta, footer {{ color:#999; }}
     td, th {{ border-color:#3a3a3a; }} code {{ background:#2a2a2a; }}
  }}
</style>
</head>
<body>
<h1>{title}</h1>
<p class="meta">{tool} version {version} &middot; generated {generated_at} &middot;
status: {status}{status_detail_html}</p>
<h2>Metadata</h2>
<table>
<tbody>
{metadata_rows}
</tbody>
</table>
<h2>Findings ({finding_count})</h2>
<table>
<thead><tr>{headers}</tr></thead>
<tbody>
{body_rows}
</tbody>
</table>
<footer>
Generated by {tool} &middot; Author: {author} &middot;
Support: <a href="{support}">{support}</a> &middot; {authorized_use}
</footer>
</body>
</html>
"""

_COLUMN_TITLES = {
    "endpoint": "Endpoint",
    "parameter": "Parameter",
    "category": "Category",
    "source": "Source",
    "source_context": "Extraction context",
    "discovery_confidence": "Discovery",
    "discovery_score": "Score",
    "behavior_confidence": "Behavior",
    "behavior_score": "B-Score",
    "manual_review_priority": "Review priority",
    "priority_reasons": "Reasons",
    "observed_differences": "Observed differences",
    "reflection_status": "Reflection",
    "validation_attempts": "Attempts",
    "inconclusive": "Inconclusive",
    "status_note": "Notes / errors",
    "reproduction_request": "Sanitized reproduction request",
    "limitations": "Limitations",
}


def render_html_report(
    metadata: dict[str, Any], rows: list[dict[str, Any]]
) -> str:
    headers = "".join(f"<th>{_ESCAPE(_COLUMN_TITLES.get(c, c))}</th>" for c in COLUMNS)
    body_rows: list[str] = []
    for row in rows:
        cells = []
        for col in COLUMNS:
            value = row.get(col, "")
            text = "" if value is None else str(value)
            cells.append(_cell_html(col, _ESCAPE(text)))
        body_rows.append("<tr>" + "".join(cells) + "</tr>")

    meta_items = [
        ("Tool", f"{_ESCAPE(str(metadata.get('tool', '')))} "
                 f"v{_ESCAPE(str(metadata.get('version', '')))}"),
        ("Author", _ESCAPE(str(metadata.get("author", "")))),
        ("Contact", _ESCAPE(str(metadata.get("contact", "")))),
        ("Support", _ESCAPE(str(metadata.get("support", "")))),
        ("Command", "<code>" + _ESCAPE(str(metadata.get("command", ""))) + "</code>"),
        ("Mode", _ESCAPE(str(metadata.get("mode", "")))),
        ("Status", _ESCAPE(str(metadata.get("status", "")))),
    ]
    scope = metadata.get("scope") or []
    if scope:
        meta_items.append(
            ("Scope", "<br>".join("<code>" + _ESCAPE(s) + "</code>" for s in scope))
        )
    totals = metadata.get("totals") or {}
    if totals:
        total_lines = "<br>".join(
            f"{_ESCAPE(k.replace('_', ' '))}: {_ESCAPE(str(v))}" for k, v in totals.items()
        )
        meta_items.append(("Totals", total_lines))
    limitations = metadata.get("limitations") or []
    if limitations:
        meta_items.append(
            ("Limitations",
             "<br>".join(_ESCAPE(str(x)) for x in limitations[:20]))
        )
    status_detail = str(metadata.get("status_detail") or "")
    status_detail_html = (
        f"<br><span class='meta'>{_ESCAPE(status_detail)}</span>" if status_detail else ""
    )
    metadata_rows = "".join(
        f"<tr><th>{k}</th><td>{v}</td></tr>" for k, v in meta_items
    )
    page = _HTML.format(
        title=_ESCAPE(f"{metadata.get('tool', 'ParamScout')} report "
                      f"- {metadata.get('command', '')}"),
        tool=_ESCAPE(str(metadata.get("tool", ""))),
        version=_ESCAPE(str(metadata.get("version", ""))),
        generated_at=_ESCAPE(str(metadata.get("generated_at", ""))),
        status=_ESCAPE(str(metadata.get("status", ""))),
        status_detail_html=status_detail_html,
        metadata_rows=metadata_rows,
        finding_count=len(rows),
        headers=headers,
        body_rows="".join(body_rows),
        author=_ESCAPE(str(metadata.get("author", ""))),
        support=_ESCAPE(str(metadata.get("support", ""))),
        authorized_use=_ESCAPE(str(metadata.get("authorized_use", ""))),
    )
    return page


def _cell_html(column: str, escaped: str) -> str:
    if column in ("endpoint", "reproduction_request", "source_context"):
        return f"<td><code>{escaped}</code></td>"
    if column == "manual_review_priority":
        color = _PRIORITY_STYLE.get(escaped, "#444444")
        return f'<td><span class="pill" style="background:{color}">{escaped}</span></td>'
    return f"<td>{escaped}</td>"
